# SPDX-License-Identifier: GPL-2.0
CFLAGS += -Wall

TEST_GEN_PROGS = test_dmabuf_cgroup_transfer

include ../../../lib.mk

$(OUTPUT)/test_dmabuf_cgroup_transfer: ../../../cgroup/cgroup_util.c binder_util.c
